#!/bin/bash

function color_my_prompt {
    local __user_and_host="\[\033[01;33m\]\u@\h"
    # local __cur_location="\[\033[01;33m\]\w"
    local __cur_location="\[\033[33m\]\w"
    local __git_branch_color="\[\033[32m\]"
    local __git_branch='`git branch 2> /dev/null | grep -e ^* | sed -E  s/^\\\\\*\ \(.+\)$/\(\\\\\1\)\ /`'
    #local __prompt_tail="\[\033[37m\]\u'1F601'"
    local __prompt_tail="\[\033[37m\]$"
    local __last_color="\[\033[00m\]"
    # export PS1="$__user_and_host $__cur_location $__git_branch_color$__git_branch$__prompt_tail$__last_color "
    export PS1="$__cur_location $__git_branch_color$__git_branch$__prompt_tail$__last_color "
}
